### ISSUE TITLE
issue with api docs and shortcodes

### ISSUE THREAD

**Issue by susanev** [equinix/pulumi-equinix#10]
we werent able to merge this into the registry
because of a build failure

more deets in
https://github.com/pulumi/registry/pull/2409

pls reach out if i can help in anyway, thank you!

**Comment by ctreatma** [comment]
@susanev I found one closing shortcode in the wrong place in our docs; is there a way I can replicate the failed build mentioned in this issue?  If possible I'd like to verify that we completely fixed the docs before publishing a release.

**Comment by susanev** [comment]
Hi @ocobleseqx, apologies but we don't have an easy easy to do this today. I'll let ya know if anything else comes up.

**Comment by ctreatma** [comment]
This and #9 are included in the v0.2.1 release that just went out.
