### ISSUE TITLE
auto download of equinix plugin is not working

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/pulumi-equinix#13]
![image](https://github.com/equinix/pulumi-equinix/assets/68897552/fc156cd0-5daa-417e-bb54-6e82010ff765)

**Comment by ctreatma** [comment]
This could be an IP-based GitHub rate limit issue.  I was able to download the darwin_arm64 build anonymously with `curl`.  I'll try fetching with pulumi as well, just to make sure it's not an issue somewhere in there.

**Comment by ocobleseqx** [comment]
https://github.com/pulumi/pulumi/issues/12867
