### ISSUE TITLE
Go get: module declares its path as: fake_java_module

### ISSUE THREAD

**Issue by DevGuyOps** [equinix/pulumi-equinix#14]
Hey 👋🏻,

I am trying to use this new library to spin up my metal infra but when I try to do a go get I get the below error.
```bash
go: github.com/equinix/pulumi-equinix@v0.2.1: parsing go.mod:
        module declares its path as: fake_java_module
                but was required as: github.com/equinix/pulumi-equinix
```

I tried the go get using the example in the README but didn't work `go get github.com/equinix/pulumi-equinix/sdk/go/...`.

Any help would be much appreciated 🙏🏻

**Comment by displague** [comment]
This will be fixed in v0.3 (just needs to be tagged, should be later today)
