### ISSUE TITLE
Does not contain packages matching github.com/equinix/pulumi-equinix/sdk/go/...

### ISSUE THREAD

**Issue by DevGuyOps** [equinix/pulumi-equinix#46]
Hi,

Just trying to do a go get for this package and I run into the below issue.

```bash
go get -u github.com/equinix/pulumi-equinix/sdk/go/...
go: module github.com/equinix/pulumi-equinix@upgrade found (v0.5.1), but does not contain packages matching github.com/equinix/pulumi-equinix/sdk/go/...
```

I'm not sure how to get around this issue and any help you could provide would be great thanks.

**Comment by ocobles** [comment]
Hi @DevGuyOps can you please try again? in case still not working please clean cache first

```
go clean -cache  
go clean -modcache
```

**Comment by DevGuyOps** [comment]
I just tried and managed to get it to import.

Thanks for the help!
