### ISSUE TITLE
Unable to create Metal Interconnection

### ISSUE THREAD

**Issue by srushti-patl** [equinix/pulumi-equinix#94]
Getting the following error while creating Metal Interconnection with type shared_port_vlan
`  error: Failed to prepare a resource encoder: cannot derive an encoder for resource "equinix_metal_connection": Cannot derive an encoder for property "ports": issue deriving an object encoder: Cannot derive an encoder for property "virtual_circuit_ids": when deriving converters for an element of a collection: LookupSchemaPath failed at walk.NewSchemaPath(): walk.ElementStep{} is not applicable`

 tried to create the Fabric billed metal interconnection but still getting the same error.

**Comment by ocobles** [comment]
fix included in https://github.com/equinix/pulumi-equinix/pull/104
