### ISSUE TITLE
No Pulumi plugin binaries released for v0.11.0

### ISSUE THREAD

**Issue by ringods** [equinix/pulumi-equinix#98]
Hello, @ringods here from Pulumi.

I just noticed that you released v0.11.0 of your provider. But the v0.11.0 assets of the Github Release only has the source archives. The plugin binaries are missing from this release:

https://github.com/equinix/pulumi-equinix/releases/tag/v0.11.0

The absence of the plugin binaries will result in errors when using in a Pulumi project because you configure the Github Release to be the source to retrieve the plugin binaries from:

https://github.com/equinix/pulumi-equinix/blob/9d4f110d966318ff313e92579458a5231fc42ca7/provider/resources.go#L120

Previous releases had the plugin binaries correctly included in the release:

https://github.com/equinix/pulumi-equinix/releases/tag/v0.10.0
https://github.com/equinix/pulumi-equinix/releases/tag/v0.9.1

**Comment by ocobles** [comment]
thanks @ringods, I'll take a look
